### ISSUE TITLE
Missing notification

### ISSUE THREAD

**Issue by LouisBaranger** [convertersystems/opc-ua-client#217]
Hello,

I'm working with your client with a Siemens CPU 1500 server. 

It works well except sometimes, quite randomly, I don't get the notification from some changes on monitored items.
I have watched on PLC, the item has changed of value.
I don't have any exceptions, neither notification for this new value. 
I used Wireshark to see what append on Tcp and I don't see any dataChange for this item.

If I manualy change the value few seconds later, I'm getting a notification...

Some details about my sub and items.
Subscriptions : 
Publish interval : 500,
Lifetime count : 600,
MaxKeepAlive : 60

MonitoredItems :
Sampling interval : 500
Queue Size : 10
DiscardOldest : True

This problem is blocking my program because I wait the end of a process with a subscription on PLC but sometimes, I never get it.

Thanks,

PS :  I already have watched the bkohlmaier issue, I think this is the same problem.

**Comment by awcullen** [comment]
Hi Louis,

I would like to learn more about your program, for example: subscription count, items per subscription.  You mentioned you have experience with Wireshark. Could you share some details about the returned values from CreateSubscriptionResponse and CreateMonitoredItemsResponse?
 
Also, I am curious if you can share the PublishResponse. If the server sends a PublishResponse and the client doesn't acknowledge it. There will be a growing list of AvailableSequenceNumbers.  

If you are on a tight schedule with your project, maybe you can program a periodic read of this Item and determine the end of your process that way.   

I do hope to find the source of this bug since both you and bkohlmaier have reported it.

Andrew

**Comment by LouisBaranger** [comment]
Thanks for your interest,

It's a variable application, in this case, I use 1 session, 1 sub, 68 monitored items, it can be in the worse case around 200 monitored items. I tested to read all this items (200), it takes me around 1200ms...

I have checked the AvailableSequenceNumbers in publish around the bug, the array size is always 0.

Here you can see some capture from Wireshark. 
GitHub doesn't support .pcapng file, if you give me an email I can send you all the detail.

Channel response
![ChannelResponse](https://user-images.githubusercontent.com/95295147/146340023-e619ef0c-b1f8-4af4-a94a-c7eeeb1876fd.PNG)

Session Response
![SessionResponse](https://user-images.githubusercontent.com/95295147/146340400-7c6c4829-595f-44a0-b4d5-73e6c2184148.PNG)

Subscription Response
![SubscriptionResponse](https://user-images.githubusercontent.com/95295147/146340467-8b68a049-37bb-4c78-94e8-be6730ae93df.PNG)

MonitoredItem Response
![MonitoredItemResponse](https://user-images.githubusercontent.com/95295147/146340547-62fe5ae1-f0d5-4006-986f-7ff61295e87f.PNG)

Publish Request
![PublishRequest](https://user-images.githubusercontent.com/95295147/146340627-43a75179-93c6-4b74-bbf0-d2e74e25f0a8.PNG)

Publish Response
![PublishResponse](https://user-images.githubusercontent.com/95295147/146340661-4228fce3-5565-48a2-a591-36936216de1a.PNG)

**Comment by awcullen** [comment]
Thanks for all the good info. 

I setup a test using PLCSim with a tag that increments every 0.1 s.  The ua server settings are:

![image](https://user-images.githubusercontent.com/11900570/146619585-c8e0e382-839f-4691-9dba-280e3b2f239d.png)

I wrote a console app to log the data change notifications. The item is set to sample at 1s and the subscription is set to publish at the same rate.
I also tested sampling at 1s and publishing at 2s.  In this case, I get PublishResponse every 2s, but the response has two notifications in it.  

An alternative to subscription is to read the list of nodes.  You may notice that reading can be slower.  To speed up reading you pass the list of nodes to the RegisterNodes method.  The response gives you a list of nodeID that use to read instead of the original.  [Let me know if you would like an example]
  
Info about RegisterNodes  is here: https://reference.opcfoundation.org/v104/Core/docs/Part4/5.8.5/

**Comment by awcullen** [comment]
I found an example 
```
        private static async Task TestAsync2()
        {

            // var discoveryUrl = "opc.tcp://localhost:48010"; // UaCppServer - see  http://www.unified-automation.com/
            var discoveryUrl = $"opc.tcp://192.168.1.94:4840"; // Siemens

            Console.WriteLine("Step 1 - Describe this app.");
            var appDescription = new ApplicationDescription()
            {
                ApplicationName = "MyHomework",
                ApplicationUri = $"urn:{System.Net.Dns.GetHostName()}:MyHomework",
                ApplicationType = ApplicationType.Client,
            };

            Console.WriteLine("Step 2 - Create a certificate store.");
            var certificateStore = new DirectoryStore(
                Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Workstation.ConsoleApp", "pki"));

            Console.WriteLine("Step 3 - Create a session with your server.");
            var channel = new UaTcpSessionChannel(
                appDescription,
                certificateStore,
                ShowSignInDialog,
                discoveryUrl);
            try
            {
                await channel.OpenAsync();

                Console.WriteLine($"  Opened channel with endpoint '{channel.RemoteEndpoint.EndpointUrl}'.");
                Console.WriteLine($"  SecurityPolicyUri: '{channel.RemoteEndpoint.SecurityPolicyUri}'.");
                Console.WriteLine($"  SecurityMode: '{channel.RemoteEndpoint.SecurityMode}'.");
                Console.WriteLine($"  UserIdentity: '{channel.UserIdentity}'.");

                Console.WriteLine("Press any key to continue...");
                Console.ReadKey(true);

                // Prepare array of nodes to read.
                var registerNodesRequest = new RegisterNodesRequest
                {
                    NodesToRegister = new[]
                    {
                        NodeId.Parse("ns=3;s=\"TestData\".\"TestVector\".\"X\""),
                    }
                };

                var registerNodesResponse = await channel.RegisterNodesAsync(registerNodesRequest).ConfigureAwait(false);

                // Read the nodes.
                var readRequest = new ReadRequest
                {
                    NodesToRead = registerNodesResponse.RegisteredNodeIds.Select(
                        id => new ReadValueId { NodeId = id, AttributeId = AttributeIds.Value })
                    .ToArray()
                };

                Console.WriteLine("Press any key to end the program...");

                while (!Console.KeyAvailable)
                {
                    // Read the nodes.
                    var readResponse = await channel.ReadAsync(readRequest).ConfigureAwait(false);

                    // Write the results.
                    for (int i = 0; i < readRequest.NodesToRead.Length; i++)
                    {
                        Console.WriteLine($"{readRequest.NodesToRead[i].NodeId}; value: {readResponse.Results[i]}");
                    }

                    await Task.Delay(1000);
                }
                await channel.CloseAsync();
            }
            catch (ServiceResultException ex)
            {
                if ((uint)ex.HResult == StatusCodes.BadSecurityChecksFailed)
                {
                    Console.WriteLine("Error connecting to endpoint. Did the server reject our certificate?");
                }

                await channel.AbortAsync();
                throw;
            }
        }
```

**Comment by LouisBaranger** [comment]
Thank you all,

I actually do a request (Set a bit at true) and waits for an answer (An other bit at true).
So the request answer bit is always true until I write false on the request but I get no notification of this change.

I will try to read with RegisterNodes later, I hope I can read all my 200 variables in less than 500ms.
